#!/bin/bash

showUsage() {
	printf "Usage:\n"
	printf "\tclassman help\n"
	printf "\tclassman help <action>\n"
	printf "\tclassman collect -s </path/to/studentfile> -t <tag>\n"
	printf "\tclassman create -s </path/to/studentfile>\n"
	printf "\tclassman publish -a </path/to/assignment> -s </path/to/studentfile>\n"
	printf "\tclassman return -s </path/to/studentfile> -p </path/to/assignments> -f <tag>\n"
	exit 1
}

getHelpPage() {
	case $1 in
		collect)
			man classman_collect
			;;
		create)
			man classman_create
			;;
		publish)
			man classman_publish
			;;
		return)
			man classman_return
			;;
		*)
			printf "No man page for that action\n"
			man classman_help
	esac

	exit 1
}





action="$1"
helpPage="$2"
instructor="$USER"

if groups $instructor | grep "\binstructors\b" && [[ ! -z $instructor ]]; then
	echo "ready to go!"
fi

# Need to shift the positional arguments so that getopts can start from $1
shift

while getopts ":t:s:p:f:a:g:" opt; do
	case $opt in
		a)
			Aflag="$OPTARG"
			;;
		f)
			Fflag="$OPTARG"
			;;
		p)
			Pflag="$OPTARG"
			;;
		s)
			Sflag="$OPTARG"
			;;
		t)
			Tflag="$OPTARG"
			;;
		g)
			Gflag="$OPTARG"
			;;
		*)
			showUsage
	esac
done

case $action in
	collect)
		sudo bash $HOME/itr/bash/collectHomework.sh -i $instructor -s $Sflag -t $Tflag
		#sudo bash $HOME/itr/bash/collectHomework.sh -i $instructor -s $Sflag -t $Tflag -g $Gflag
		;;
	create)
		sudo bash $HOME/itr/bash/createDirectories.sh -i $instructor -s $Sflag
		#sudo bash $HOME/itr/bash/createDirectories.sh -i $instructor -s $Sflag -g $Gflag
		;;
	help)
		getHelpPage $helpPage
		;;
	publish)
		sudo bash $HOME/itr/bash/publishHomework.sh -a $Aflag -s $Sflag
		#sudo bash $HOME/itr/bash/publishHomework.sh -a $Aflag -s $Sflag -g $Gflag
		;;
	return)
		sudo bash $HOME/itr/bash/returnHomework.sh -i $instructor -s $Sflag -p $Pflag -f $Fflag
		#sudo bash $HOME/itr/bash/returnHomework.sh -i $instructor -s $Sflag -p $Pflag -f $Fflag -g $Gflag
		;;
	*)
		showUsage
esac
