.TH publishHomework.sh 1 "16 April 2016" "itr/bash/publishHomework.sh" "Manual: classman publish"

.SH NAME
classman publish \- copies file or directory into student's $HOME/assignments directory.

.SH SYNOPSIS
classman publish -s </path/to/studentfile> -a </path/to/assignemnt>

.SH DESCRIPTION
.B classman publish
copies a file or directory given by the
.B -a
option to each student in the file provided by the
.B -s
option. Permissions are changed to 770 on the assignment file so that students can read, write, and execute any file including PDFs and R Studio projects.
.PP
The file executed is found at itr/bash/publishHomework.sh

.SH OPTIONS
.IP -s
Path to the file containing a list of student usernames that will be receive the assignment file or directory.
.IP -a
Path to the file to be copied to a student's $HOME/assignments directory
.SH SEE ALSO
.B classman help collect
.PP
.B classman help create
.PP
.B classman help publish
.PP
.B classman help return

.SH AUTHOR
Cameron Everett (cameronjeverett@gmail.com)
